# Generated by Django 3.0.1 on 2019-12-21 06:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeerHarvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('bucks', models.IntegerField()),
                ('does', models.IntegerField()),
                ('total_harvest', models.IntegerField()),
                ('total_hunters', models.IntegerField()),
                ('total_rec_days', models.IntegerField()),
                ('percent_sucess', models.IntegerField()),
                ('section_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElkHarvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('bulls', models.IntegerField()),
                ('cows', models.IntegerField()),
                ('total_harvest', models.IntegerField()),
                ('total_hunters', models.IntegerField()),
                ('total_rec_days', models.IntegerField()),
                ('percent_sucess', models.IntegerField()),
                ('section_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LandTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('type_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PronhornHarvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('bucks', models.IntegerField()),
                ('does', models.IntegerField()),
                ('total_harvest', models.IntegerField()),
                ('total_hunters', models.IntegerField()),
                ('total_rec_days', models.IntegerField()),
                ('percent_sucess', models.IntegerField()),
                ('section_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PublicLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('land_type', models.IntegerField()),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('center_point', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('total_public', models.FloatField()),
                ('total_private', models.FloatField()),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('center_point', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='WalkInAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('land_type', models.IntegerField()),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('center_point', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
