# Generated by Django 3.0.1 on 2019-12-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvesttitles',
            old_name='name',
            new_name='title',
        ),
    ]
