# Generated by Django 3.0.1 on 2019-12-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_auto_20191221_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicland',
            name='square_feet',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='unit',
            name='square_feet',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='walkinaccess',
            name='square_feet',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='deerharvest',
            name='section_title',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='elkharvest',
            name='section_title',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pronhornharvest',
            name='section_title',
            field=models.IntegerField(),
        ),
    ]
